[package]
name = "railroad"
version = "0.1.0"
authors = ["Lukas Lueg <lukas.lueg@gmail.com>"]
license = "MIT"
description = "A library to create syntax-diagrams as Scalable Vector Graphics"

[features]
visual-debug = []

[dependencies]
htmlescape = "0.3"
unicode-width = "0.1"
